# Generated by Django 5.2.9 on 2025-12-02 19:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('village', models.CharField(max_length=100)),
                ('traditional_authority', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('business_industry', models.CharField(choices=[('FARMING', 'Farming'), ('FISHING', 'Fishing'), ('TRADING', 'Trading'), ('TRANSPORT', 'Transport'), ('CIVIL_SERVANT', 'Civil Servant'), ('RETAIL', 'Retail'), ('CONSTRUCTION', 'Construction'), ('HOSPITALITY', 'Hospitality'), ('TAILORING', 'Tailoring'), ('CARPENTRY', 'Carpentry'), ('OTHER', 'Other')], max_length=50)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('transport_mode', models.CharField(choices=[('FOOT', 'On Foot'), ('BICYCLE', 'Bicycle'), ('MOTORBIKE', 'Motorbike'), ('CAR', 'Car'), ('MINIBUS', 'Minibus')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LILONGWE', 'Lilongwe Branch'), ('KASUNGU', 'Kasungu Branch'), ('SALIMA', 'Salima Branch'), ('NKHOTAKOTA', 'Nkhotakota Branch'), ('MZUZU', 'Mzuzu Branch'), ('BLANTYRE', 'Blantyre Branch'), ('MSANJE', 'Msanje Branch'), ('MCHINJI', 'Mchinji Branch'), ('KARONGA', 'Karonga Branch')], max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='MacroMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField(unique=True)),
                ('gdp_growth_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('inflation_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('unemployment_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('exchange_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_rate_policy', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Macro Monthly Data',
                'ordering': ['-month_date'],
            },
        ),
        migrations.CreateModel(
            name='GroupRiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(blank=True, choices=[('BUSINESS', 'Business Loan'), ('PAYDAY', 'PayDay Loan'), ('YOUTH', 'Youth Loan'), ('WOMEN', 'Women Loan'), ('MEN', 'Men Loan')], max_length=20, null=True)),
                ('tenure_months', models.IntegerField(blank=True, null=True)),
                ('mean_pd', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('mean_lgd', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('total_ead', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_expected_loss', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('par30_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('par60_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('par90_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('recovery_rate', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('loan_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='core.branch')),
            ],
            options={
                'verbose_name_plural': 'Group Risk Metrics',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('national_id', models.CharField(max_length=20)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('relationship_to_borrower', models.CharField(choices=[('PARENT', 'Parent'), ('SIBLING', 'Sibling'), ('FRIEND', 'Friend'), ('RELATIVE', 'Relative'), ('BUSINESS_PARTNER', 'Business Partner'), ('OTHER', 'Other')], max_length=30)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('phone', models.CharField(max_length=20)),
                ('collateral_backing', models.BooleanField(default=False)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(max_length=20, unique=True)),
                ('loan_type', models.CharField(choices=[('BUSINESS', 'Business Loan'), ('PAYDAY', 'PayDay Loan'), ('YOUTH', 'Youth Loan'), ('WOMEN', 'Women Loan'), ('MEN', 'Men Loan')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('disbursement_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('4.0'), max_digits=5)),
                ('disbursement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tenure_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('application_date', models.DateField()),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted'), ('WRITTEN_OFF', 'Written Off')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.borrower')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Collateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_name', models.CharField(max_length=200)),
                ('collateral_type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORBIKE', 'Motorbike'), ('LAND_CERTIFICATE', 'Land Certificate'), ('LIVESTOCK', 'Livestock'), ('HOUSEHOLD_ITEMS', 'Household Items'), ('TV_RADIO', 'TV/Radio'), ('FISHING_GEAR', 'Fishing Gear'), ('VEHICLE', 'Vehicle'), ('TITLE_DEED', 'Title Deed'), ('STOCK', 'Stock')], max_length=30)),
                ('description', models.TextField()),
                ('valuation_date', models.DateField()),
                ('appraised_value_mwk', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('market_value_estimate_mwk', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=20)),
                ('owner_type', models.CharField(choices=[('BORROWER', 'Borrower'), ('SPOUSE', 'Spouse'), ('GUARANTOR', 'Guarantor')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collateral_items', to='core.loan')),
            ],
            options={
                'verbose_name_plural': 'Collateral',
            },
        ),
        migrations.CreateModel(
            name='LoanOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('hire_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_officers', to='core.branch')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='core.loanofficer'),
        ),
        migrations.CreateModel(
            name='LoanRiskMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_mean', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('pd_lower_hdi', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('pd_upper_hdi', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('lgd_mean', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('lgd_lower_hdi', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('lgd_upper_hdi', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('ead', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('expected_loss', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('hazard_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metric', to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Recovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recovery_date', models.DateField()),
                ('recovery_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recovery_method', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Spouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('SELF_EMPLOYED', 'Self-Employed'), ('UNEMPLOYED', 'Unemployed'), ('STUDENT', 'Student')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('relationship_start_date', models.DateField()),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('scheduled_date', models.DateField()),
                ('scheduled_principal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scheduled_interest', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scheduled_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('actual_payment_date', models.DateField(blank=True, null=True)),
                ('actual_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('payment_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ON_TIME', 'On Time'), ('LATE_PAYMENT', 'Late Payment'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('MISSED_PAYMENT', 'Missed Payment')], default='SCHEDULED', max_length=20)),
                ('days_late', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.loan')),
            ],
            options={
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
