# Generated by Django 5.2.9 on 2025-12-03 12:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField(auto_now_add=True)),
                ('loan_usage_intention', models.TextField()),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('past_defaults', models.BooleanField(default=False)),
                ('client_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cluster_group', models.CharField(blank=True, choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10, null=True)),
                ('recommended_loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='core.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('business_age_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_costs', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stock_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('number_of_employees', models.IntegerField(default=0)),
                ('seasonality_index', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_assessments', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residence_type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('TEMPORARY', 'Temporary'), ('RELATIVE', 'Relative')], max_length=20)),
                ('months_at_residence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_dependents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('total_monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('net_monthly_cashflow', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('liquid_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('stability_index', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='household_assessment', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='InformalLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('repayment_schedule', models.CharField(max_length=100)),
                ('balance_remaining', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informal_loans', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='TrustGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.CharField(choices=[('SPOUSE', 'Spouse'), ('GUARANTOR', 'Guarantor')], max_length=20)),
                ('participant_name', models.CharField(max_length=100)),
                ('support_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('intervention_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trust_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_games', to='core.clientscreening')),
            ],
        ),
    ]
