# Generated by Django 5.2.8 on 2025-12-03 19:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_clientscreening_businessassessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessassessment',
            name='stock_value',
        ),
        migrations.RemoveField(
            model_name='householdassessment',
            name='months_at_residence',
        ),
        migrations.RemoveField(
            model_name='householdassessment',
            name='number_of_dependents',
        ),
        migrations.RemoveField(
            model_name='householdassessment',
            name='residence_type',
        ),
        migrations.RemoveField(
            model_name='householdassessment',
            name='stability_index',
        ),
        migrations.RemoveField(
            model_name='informalloan',
            name='balance_remaining',
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='business_photo',
            field=models.ImageField(blank=True, null=True, upload_to='business_photos/'),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='daily_food_at_shop',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='daily_selling_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='daily_transport_home_to_shop',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='monthly_food_supplier_trips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='monthly_salaries',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='monthly_transport_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='monthly_utilities',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='businessassessment',
            name='number_of_outlets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='clientscreening',
            name='guarantor_recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='clientscreening',
            name='loan_ratio',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='clientscreening',
            name='spouse_recommended_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='householdassessment',
            name='household_stability_years',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='householdassessment',
            name='potential_shocks_discussed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informalloan',
            name='community_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informalloan',
            name='guarantor_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informalloan',
            name='lender_relationship',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informalloan',
            name='receipt_upload',
            field=models.FileField(blank=True, null=True, upload_to='informal_loan_receipts/'),
        ),
        migrations.AddField(
            model_name='informalloan',
            name='spouse_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessassessment',
            name='business_age_years',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='businessassessment',
            name='business_type',
            field=models.CharField(choices=[('TRADE', 'Trade'), ('SERVICES', 'Services'), ('AGRICULTURE', 'Agriculture'), ('MANUFACTURING', 'Manufacturing'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='businessassessment',
            name='monthly_profit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businessassessment',
            name='number_of_employees',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clientscreening',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_screenings', to='core.borrower'),
        ),
        migrations.AlterField(
            model_name='clientscreening',
            name='cluster_group',
            field=models.CharField(blank=True, choices=[('LOW', 'Low Risk - Accept'), ('MEDIUM', 'Medium Risk - Conditional'), ('HIGH', 'High Risk - Reject')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='householdassessment',
            name='net_monthly_cashflow',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='BehavioralVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_cashflow_answer', models.TextField()),
                ('key_suppliers_answer', models.TextField()),
                ('key_clients_answer', models.TextField()),
                ('business_routine_answer', models.TextField()),
                ('answered_by_proxy', models.BooleanField(default=False)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_verification', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity_sold_per_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('buying_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_stock_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_items', to='core.businessassessment')),
            ],
        ),
        migrations.CreateModel(
            name='ClientCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('LAND', 'Land'), ('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('STOCK', 'Stock/Inventory'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ownership_verified', models.BooleanField(default=False)),
                ('physical_condition', models.CharField(choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=20)),
                ('seizure_difficulty', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('photo_upload', models.ImageField(blank=True, null=True, upload_to='client_collateral_photos/')),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='client_collateral_docs/')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_collaterals', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('NONE', 'No Formal Education'), ('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('TERTIARY', 'Tertiary')], max_length=20)),
                ('residence_type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('TEMPORARY', 'Temporary'), ('RELATIVE', 'Living with Relative')], max_length=20)),
                ('months_at_residence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_dependents', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('number_of_active_businesses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('VOTER_CARD', 'Voter Card')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('home_visit_conducted', models.BooleanField(default=False)),
                ('proxy_applicant_detected', models.BooleanField(default=False)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship_to_client', models.CharField(max_length=100)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('liquid_assets', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('voluntary_guarantor', models.BooleanField()),
                ('has_past_defaults', models.BooleanField(default=False)),
                ('q_willingness_to_repay', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('q_aware_of_debts', models.BooleanField()),
                ('q_incentive_alignment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('q_past_reliability', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('trust_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantor_assessments', to='core.clientscreening')),
            ],
        ),
        migrations.CreateModel(
            name='GuarantorCollateral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collateral_type', models.CharField(choices=[('LAND', 'Land'), ('VEHICLE', 'Vehicle'), ('EQUIPMENT', 'Equipment'), ('STOCK', 'Stock/Inventory'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ownership_verified', models.BooleanField(default=False)),
                ('physical_condition', models.CharField(choices=[('POOR', 'Poor'), ('FAIR', 'Fair'), ('GOOD', 'Good'), ('EXCELLENT', 'Excellent')], max_length=20)),
                ('seizure_difficulty', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('document_upload', models.FileField(blank=True, null=True, upload_to='guarantor_collateral_docs/')),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaterals', to='core.guarantorassessment')),
            ],
        ),
        migrations.CreateModel(
            name='SpouseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('supports_loan', models.BooleanField()),
                ('aware_of_debts', models.BooleanField()),
                ('financial_involvement', models.CharField(choices=[('NONE', 'None'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('decision_making_power', models.CharField(choices=[('NONE', 'None'), ('PARTIAL', 'Partial'), ('FULL', 'Full')], max_length=10)),
                ('q_support_repayment', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('q_intervene_if_missed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('cooperation_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('screening', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_assessment', to='core.clientscreening')),
            ],
        ),
        migrations.DeleteModel(
            name='TrustGame',
        ),
    ]
